---
- name: install system packages
  become: true
  package:
    name:
      - "git"
      - "{{ python_libselinux[ansible_pkg_mgr] }}"
      - "{{ python_setuptools[ansible_pkg_mgr] }}"
      - "{{ python_virtualenv[ansible_pkg_mgr] }}"
      - "{{ python_pip[ansible_pkg_mgr] }}"
    state: present

- name: pip install tripleo-repos
  become: true
  pip:
    name: "{{ tripleo_repos_repository }}"
    virtualenv: "{{ workspace }}/venv"
    virtualenv_python: "{{ virtualenv_python[ansible_pkg_mgr] }}"
    virtualenv_site_packages: true

- name: Get branch
  set_fact:
    ci_branch: "{{ zuul.branch | default('master') | replace('stable/','') }}"
  when: zuul is defined

- name: Install repos
  become: true
  shell: |
    set -ex
    source {{ workspace }}/venv/bin/activate
    if [ -f /etc/ci/mirror_info.sh ]; then
      source /etc/ci/mirror_info.sh
      DISTRO_MIRROR_HOST="http://${NODEPOOL_MIRROR_HOST}"
    fi
    {% if ansible_distribution | lower == 'fedora' %}
    DISTRO_MIRROR_HOST=${DISTRO_MIRROR_HOST:-"{{ fedora_mirror_host }}"}
    {% else %}
    DISTRO_MIRROR_HOST=${DISTRO_MIRROR_HOST:-"{{ centos_mirror_host }}"}
    {% endif %}
    RDO_MIRROR_HOST=${NODEPOOL_RDO_PROXY:-"{{ rdo_mirror_host }}"}

    if [ "{{ override_repos }}" != "" ]; then
        REPO="{{ override_repos }}"
    elif [ "{{ ci_branch | default('master') }}" == "master" ]; then
        REPO=current-tripleo
    else
        REPO=current
    fi

    tripleo-repos \
      -b "{{ ci_branch | default('master') }}" \
      --mirror $DISTRO_MIRROR_HOST \
      --rdo-mirror $RDO_MIRROR_HOST $REPO
  register: result
  changed_when: "'Installed:' in result.stdout_lines"

# TODO(rfolco): normalize centos/fedora repo names, fedora sets delorean.repo and fedora-stable.repo,
# while centos sets delorean.repo and delorean-master-testing.repo.
- name: rename fedora-stable.repo
  become: true
  shell: |
    set -ex
    # Rename fedora-stable.repo as kola.conf.j2 template expects delorean*
    mv /etc/yum.repos.d/fedora-stable.repo /etc/yum.repos.d/delorean-master-testing.repo
  when: ansible_distribution|lower  == "fedora"
