workspace: "{{ ansible_user_dir }}/workspace"
openstack_git_root: "{{ ansible_user_dir }}/src/opendev.org/openstack"

# https://review.opendev.org/#/c/669471 - rhel8 kolla support
kolla_rhel8_patch:
  master: 669471
  "stable/train": 693159

virtualenv_python:
  yum: python
  dnf: python3

exclude_containers:
  dnf:
    - fluentd
    - opendaylight
    - skydive-agent
    - skydive-analyzer
    - sensu-client
    - sensu-base
  yum:
    - opendaylight
  rocky:
    - grafana

timestamper_cmd: >-
    | awk '{ print strftime("%Y-%m-%d %H:%M:%S |"), $0; fflush(); }'

# used with component_ci_service in defaults/main by component-ci jobs
component_ci_configs:
  compute: "$TRIPLEO_CI_PATH/roles/build-containers/templates/component_ci/compute_overcloud_containers.yaml"
  keystone: "$TRIPLEO_CI_PATH/roles/build-containers/templates/component_ci/keystone_overcloud_containers.yaml"
