# This file contains settings that are specific to RDO Cloud.
# These settings will override the ovb default settings

# These values are defined now in the te-broker config
# https://github.com/openstack-infra/tripleo-ci/blob/master/scripts/te-broker/create-env#L47
cloudenv: "rdo"
custom_nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 38.145.33.91
external_net: '38.145.32.0/22'
ntp_server: '0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org'
workers_args: >-
    -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e {{ overcloud_templates_path }}/environments/debug.yaml
overcloud_image_url: >-
  {% if ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8' -%}
  https://images-vexxhost.rdoproject.org:4433/rcm-guest/images/redhat8/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/overcloud-full.tar
  {%- else -%}
  http://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/overcloud-full.tar
  {%- endif %}
ipa_image_url: >-
  {% if ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8' -%}
  https://images-vexxhost.rdoproject.org:4433/rcm-guest/images/redhat8/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar
  {%- else -%}
  http://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar
  {%- endif %}
# Use cirros cached image
tempest_test_image_path: /opt/cache/files/cirros-0.3.5-x86_64-disk.img

# Container update settings
update_containers: >-
  {% if containerized_overcloud|bool or containerized_undercloud|bool -%}
  true
  {%- endif -%}

# We don't need to cleanup TripleO CI
tempest_track_resources: false

# Tempestmail settings
tempestmail_log_server: http://logs.rdoproject.org

#build-test packages
artg_repos_dir: "{{ tripleo_root }}"

# InfluxDB module settings
influxdb_only_successful_tasks: true
influxdb_measurement: job
influxdb_url: https://influxdb.review.rdoproject.org
influxdb_port: 8086
influxdb_user: tripleo_ci
influxdb_password:
influxdb_dbname: tripleo_ci
influxdb_data_file_path: "{{ artcl_collect_dir }}/influxdb_data"
influxdb_create_data_file: true

# Browbeat settings
cloud_name: rdocloud
elastic_host: browbeat.test.com
grafana_host: browbeat.test.com

# Ironic debug
# https://bugs.launchpad.net/tripleo/+bug/1797526
step_introspect_debug: true

# Ensure logs are gzipped
artcl_gzip: true
