# This file contains settings that are specific to Vexxhost
# These settings will override the ovb default settings

# These values are defined now in the te-broker config
# https://github.com/openstack-infra/tripleo-ci/blob/master/scripts/te-broker/create-env#L47
cloudenv: "vexxhost"
custom_nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 38.102.83.187
external_net: 'public'
ntp_server: '0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org'
workers_args: >-
    -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e {{ overcloud_templates_path }}/environments/debug.yaml
# Use cirros cached image
tempest_test_image_path: /opt/cache/files/cirros-0.4.0-x86_64-disk.img
tempest_tempest_conf_overrides:
  image.image_path: http://images.rdoproject.org/cirros/cirros-0.4.0-x86_64-disk.img

# Container update settings
update_containers: >-
  {% if containerized_overcloud|bool or containerized_undercloud|bool -%}
  true
  {%- endif -%}

# Rely on RDO registry instead of docker.io due to rate limit
docker_registry_host: trunk.registry.rdoproject.org

# We don't need to cleanup TripleO CI
tempest_track_resources: false

# Tempestmail settings
tempestmail_log_server: http://logs.rdoproject.org

#build-test packages
artg_repos_dir: "{{ tripleo_root }}"

# disable disk cleaning before starting installation
undercloud_clean_nodes: false

# InfluxDB module settings
influxdb_only_successful_tasks: true
influxdb_measurement: job
influxdb_url: https://influxdb.review.rdoproject.org
influxdb_port: 8086
influxdb_user: tripleo_ci
influxdb_password:
influxdb_dbname: tripleo_ci
influxdb_data_file_path: "{{ artcl_collect_dir }}/influxdb_data"
influxdb_create_data_file: true

# Browbeat settings
cloud_name: vexxhost
elastic_host: browbeat.test.com
grafana_host: browbeat.test.com

# Ironic debug
# https://bugs.launchpad.net/tripleo/+bug/1797526
step_introspect_debug: true

# Ensure logs are gzipped
artcl_gzip: true
