---
# The python_v fact is used with vars/common.yaml to set the right
# overcloud-images file in the build-images.sh.j2 template
- name: Get python_v fact for py2 or py3 common vars
  include_tasks: check_set_py3.yaml

- name: Generate build-images.sh script
  template:
    src: templates/build-images.sh.j2
    dest: "{{ workspace }}/build_images.sh"
    mode: 0777
    force: yes

- name: Run build-images.sh
  args:
    chdir: '{{ workspace }}'
  shell: bash build_images.sh > {{ workspace }}/logs/script_build.log 2> {{ workspace }}/logs/script_build-err.log
  changed_when: true

- when: rhel_image_source is defined
  block:
    - name: check if overcloud images were built
      stat:
        path: "{{ workspace }}/overcloud-full.qcow2"
      register: overcloud_stat_result

    - name: check if ipa images were built
      stat:
        path: "{{ workspace }}/ironic-python-agent.kernel"
      register: ipa_stat_result

    - when: ipa_stat_result.stat.exists|bool
      block:

        - name: ironic-python-agent
          archive:
            path:
              - "{{ workspace }}/ironic-python-agent.initramfs"
              - "{{ workspace }}/ironic-python-agent.kernel"
            dest: "{{ ansible_user_dir }}/ironic-python-agent.tar"
            format: tar

        - name: Create md5sums
          shell:
            cmd: |
              md5sum ironic-python-agent.tar > ironic-python-agent.tar.md5
          args:
            chdir: "{{ ansible_user_dir }}"

    - when: overcloud_stat_result.stat.exists|bool
      block:

        - name: overcloud-full
          archive:
            path:
              - "{{ workspace }}/overcloud-full.qcow2"
              - "{{ workspace }}/overcloud-full.initrd"
              - "{{ workspace }}/overcloud-full.vmlinuz"
            dest: "{{ ansible_user_dir }}/overcloud-full.tar"
            format: tar

        - name: Create md5sums
          shell:
            cmd: |
              md5sum overcloud-full.tar > overcloud-full.tar.md5
          args:
            chdir: "{{ ansible_user_dir }}"
