---
- name: Include common buildimage vars
  include_vars:
    file: "common.yaml"

# get python_v fact used with vars/common.yaml to get
# python2 or python3 packages in below tasks
- name: Get python_v fact for py2 or py3 common vars
  include_tasks: check_set_py3.yaml

- name: Install pip and virtualenv
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ python_version[python_v] }}-pip"
    - "{{ python_version[python_v] }}-virtualenv"

- when: python_v == "py3"
  block:

    - name: Install python3-devel with provides pathfix.py
      package:
        name: python3-devel
        state: present
      become: true

    - name: Create a script that fixes shebang for python3
      template:
        src: pathfix_repos.sh.j2
        dest: "{{ workspace }}/pathfix_repos.sh"
        mode: u=rwx

    - name: Fix shebang path for python3
      shell: bash {{ workspace }}/pathfix_repos.sh

- name: pip install tripleo items
  become: true
  pip:
    name:
      - "file://{{ openstack_git_root }}/diskimage-builder"
      - "file://{{ openstack_git_root }}/python-tripleoclient"
      - "file://{{ openstack_git_root }}/tripleo-common"
    state: present
    virtualenv: "{{ workspace }}/venv"
