- hosts: all
  name: TripleO Setup Container Registry and repos mirror
  tasks:

    - name: Disable EPEL repos with dnf
      command: dnf config-manager --set-disabled epel epel-modular
      become: true
      changed_when: true
      when:
        - ansible_pkg_mgr == "dnf"

    - name: Disable EPEL repos with yum
      command: yum-config-manager --disable epel epel-modular
      become: true
      changed_when: true
      when:
        - ansible_pkg_mgr == "yum"

    - name: Include tripleo-repos
      include_role:
          name: tripleo-repos
      vars:
        override_repos: "{{ buildcontainers_override_repos | default('') }}"
        tripleo_repos_repository: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-repos'].src_dir }}"

    - name: Include bindep role
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/python-tripleoclient'].src_dir }}"

    - name: Run build containers pre tasks
      include_role:
        name: build-containers
        tasks_from: pre
