- hosts: all
  name: TripleO container image building job
  tasks:
    - name: Include common vars
      include_vars:
        file: "common.yaml"

    - name: Set facts for kolla-build.conf
      set_fact:
        ci_branch: "{{ zuul.branch | default('master') | replace('stable/','') }}"
        push_registry: "{{ push_registry | default('127.0.0.1:8787') }}"
        push_tag: "{{ push_tag | default('latest') }}"
        push_containers: "{{ push_containers | default(false) | bool }}"

    - name: Get contents of delorean repo baseurl for the version hash
      become: true
      shell: >
        cat /etc/yum.repos.d/delorean.repo |awk -F= '/baseurl/ {print $2}'
      register: baseurl

    - name: Set version_hash fact
      set_fact:
        version_hash: "{{ baseurl.stdout.split('/')[-1] }}"

    - name: grab kolla patch if needed
      when: ansible_pkg_mgr == "dnf"
      shell: |
        set -euxo pipefail
        git config --global user.email "zuul@openstack.org"
        git config --global user.name "Zuul"
        git remote add upstream https://git.openstack.org/openstack/kolla
        git ls-remote https://git.openstack.org/openstack/kolla | \
          grep -E refs/changes/[[:digit:]]+/{{ kolla_f28_patch }}/ | \
          awk '{print $2}' | \
          sort -t / -k 5 -g -r | \
          head -1 | \
          xargs -I{} git fetch https://git.openstack.org/openstack/kolla {} && \
          git checkout -b f28 FETCH_HEAD && \
          git pull --rebase upstream master

      args:
        chdir: "{{ openstack_git_root }}/kolla"
        warn: false
      register: result
      changed_when: "'nothing to commit, working directory clean' not in result.stdout_lines"

    - name: pip install kolla
      pip:
        name:
          - "file://{{ openstack_git_root }}/kolla"
          - "file://{{ openstack_git_root }}/tripleo-common"
          - "file://{{ openstack_git_root }}/python-tripleoclient"
        virtualenv: "{{ workspace }}/venv"
        virtualenv_python: "{{ virtualenv_python[ansible_pkg_mgr] }}"
        virtualenv_site_packages: true

    # TODO(aschultz): make the kolla-build branch aware
    - name: Generate kolla-build.conf
      template:
        src: templates/kolla-build.conf.j2
        dest: "{{ workspace }}/kolla-build.conf"
        mode: 0644
        force: yes

    - name: Run image build
      args:
        chdir: '{{ workspace }}'
      shell: |
        set -o pipefail
        source {{ workspace }}/venv/bin/activate
        TRIPLEO_COMMON_PATH="{{ openstack_git_root }}/tripleo-common"

        openstack overcloud container image build \
            --config-file $TRIPLEO_COMMON_PATH/container-images/overcloud_containers.yaml \
            --kolla-config-file {{ workspace }}/kolla-build.conf \
            {% for item in exclude_containers[ansible_pkg_mgr] %}
             --exclude {{ item }} \
            {% endfor %}
            {% if use_buildah is defined and use_buildah %}
             --use-buildah \
            {% endif %}
            2>&1 {{ timestamper_cmd }} > {{ workspace }}/build.log
        RESULT=$?
        exit $RESULT

    - name: Retrieve the images by version_hash and retag with tripleo-ci-testing if periodic
      when:
        - zuul is defined
        - "'periodic' in zuul.pipeline"
      block:
        - name: Retrieve list of built images
          shell: >
            docker images --format "{{ '{{' }}.Repository{{ '}}' }}" \
              --filter "reference=*:{{ version_hash }}"
          register: built_images

        - name: Tag images
          vars:
            image: "{{ item }}"
          include: tag.yml
          static: no
          with_items: "{{ built_images.stdout_lines }}"

