- name: Include OS distro version specific variables
  include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"

- name: install tripleo dependencies from package
  become: true
  package:
    name: "{{ tripleo_deps_from_package }}"

- name: set template override
  set_fact:
     kolla_override_path: "/usr/share/openstack-tripleo-common-containers/container-images/tripleo_kolla_template_overrides.j2"
