---
- name: Include common vars
  include_vars:
    dir: "vars"

- name: Ensure legacy workspace directory
  file:
    path: '{{ workspace }}'
    state: directory

- name: Setup docker registry
  when: ansible_distribution|lower != 'redhat'
  block:
    - name: Install ansible to run docker-playbook.yaml
      become: true
      package:
        name: ansible
        state: present

    - name: Create playbook structure
      file:
        path: '{{ workspace }}/container-registry'
        src: '{{ openstack_git_root }}/ansible-role-container-registry'
        state: link

    - name: Configure docker registry
      template:
        src: templates/docker-playbook.yaml.j2
        dest: '{{ workspace }}/docker-playbook.yaml'
        mode: 0644
        force: yes

    - name: Run ansible playbook to configure docker
      args:
        chdir: '{{ workspace }}'
      shell: |
        ansible-playbook docker-playbook.yaml --extra-vars "container_registry_deployment_user={{ ansible_user }}"

    - name: Remove ansible
      become: true
      package:
        name: ansible
        state: absent

    - include_tasks: reset_connection.yaml
      when: not use_buildah | default(false) | bool

    - name: Prepare Buildah
      become: true
      when: use_buildah | default(false) | bool
      block:
        - name: Install Buildah
          package:
            name: buildah
            state: present

        - name: Configure insecure registry
          ini_file:
            path: /etc/containers/registries.conf
            section: 'registries.insecure'
            option: registries
            value:
              - "localhost:{{ push_registry_port }}"

- name: Setup repo web service
  become: true
  when: ansible_distribution|lower != 'redhat'
  block:
    - name: Install apache
      package:
        name: httpd
        state: present

    - name: Start apache
      service:
        name: httpd
        state: started

    - name: Fetch delorean repos if present
      shell: |
          set -ex
          find /etc/yum.repos.d/ -name delorean\* | xargs -I {} cp {} /var/www/html/

    - name: Add http iptables rules from containers
      command: iptables -I openstack-INPUT 1 -p tcp --dport 80 -s 172.17.0.0/16 -j ACCEPT
      become: true
