- name: Install deps from upper-constraints
  pip:
    extra_args: "-c {{ openstack_git_root }}/requirements/upper-constraints.txt"
    requirements: "{{ openstack_git_root }}/{{ item }}/requirements.txt"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_python: "{{ virtualenv_python[ansible_pkg_mgr] }}"
  with_items:
    - kolla
    - tripleo-common
    - python-tripleoclient

- name: Installation from source
  pip:
    name:
      - "file://{{ openstack_git_root }}/kolla"
      - "file://{{ openstack_git_root }}/tripleo-common"
      - "file://{{ openstack_git_root }}/python-tripleoclient"
      - decorator
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_python: "{{ virtualenv_python[ansible_pkg_mgr] }}"

- name: set template override
  set_fact:
     kolla_override_path: "{{ openstack_git_root }}/tripleo-common/container-images/tripleo_kolla_template_overrides.j2"
