- name: Installation from source
  pip:
    name:
      - "file://{{ openstack_git_root }}/kolla"
      - "file://{{ openstack_git_root }}/tripleo-common"
      - "file://{{ openstack_git_root }}/python-tripleoclient"
      - decorator
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_python: "{{ virtualenv_python[ansible_pkg_mgr] }}"
    virtualenv_site_packages: true

- name: set template override
  set_fact:
     kolla_override_path: "{{ openstack_git_root }}/tripleo-common/container-images/tripleo_kolla_template_overrides.j2"
