- name: https://bugs.launchpad.net/tripleo/+bug/1862941 install six>=1.14.0
  pip:
    name:
      - six>=1.14.0
    extra_args: --user

- name: Install deps from upper-constraints
  when: zuul_internal is undefined
  pip:
    extra_args: "-c {{ openstack_git_root }}/requirements/upper-constraints.txt"
    requirements: "{{ openstack_git_root }}/{{ item }}/requirements.txt"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_python: "{{ virtualenv_python[ansible_distribution_major_version|int] }}"
  with_items:
    - kolla
    - tripleo-common
    - python-tripleoclient
    - tripleo-ansible

- name: Install deps from requirements
  when: zuul_internal is defined
  pip:
    requirements: "{{ openstack_git_root }}/{{ item }}/requirements.txt"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_python: "{{ virtualenv_python[ansible_distribution_major_version|int] }}"
  with_items:
    - kolla
    - openstack-tripleo-common
    - python-tripleoclient
    - tripleo-ansible

- name: Installation from source
  pip:
    name:
      - "file://{{ openstack_git_root }}/kolla"
      - "file://{{ openstack_git_root }}/{% if zuul_internal is defined %}openstack-{% endif %}tripleo-common"
      - "file://{{ openstack_git_root }}/python-tripleoclient"
      - "file://{{ openstack_git_root }}/tripleo-ansible"
      - decorator
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_python: "{{ virtualenv_python[ansible_distribution_major_version|int] }}"

- name: set template override
  set_fact:
    kolla_override_path:
      "{{ openstack_git_root }}/{% if zuul_internal is defined %}openstack-{% endif %}tripleo-common/container-images/tripleo_kolla_template_overrides.j2"
