
- hosts: all
  tasks:

    - name: Discover a branch
      block:

        - name: Set from regular Zuul branch
          set_fact:
            ci_branch: "{{ zuul.branch | regex_replace('(stable|cloudsig)/', '') }}"
          when: zuul is defined

        - name: Set from branch_override variable
          set_fact:
            ci_branch: "{{ branch_override | regex_replace('(stable|cloudsig)/', '') }}"
          when: branch_override is defined

        - name: Set from release variable (in periodic)
          set_fact:
            ci_branch: "{{ release }}"
          when: release is defined

    - name: Set branch variables
      set_fact:
        provider_job_branch: "{{ ci_branch }}"
        registry_ip_address_branch: "{'{{ ci_branch }}': '{{ hostvars[groups.all[0]].ansible_host }}'}"
        provider_dlrn_hash_branch: "{'{{ ci_branch }}': '{{ dlrn_hash|default('') }}'}"

    - name: Return Zuul data
      debug:
        msg: >-
          Running podman registry and repository on
          {{ hostvars[groups.all[0]].ansible_host | default('nowhere') }}
          for branch {{ ci_branch }}

    - name: Set registry IP address
      zuul_return:
        data:
          zuul:
            pause: true
          registry_ip_address: "{{ hostvars[groups.all[0]].ansible_host }}"
          provider_dlrn_hash: "{{ dlrn_hash|default('') }}"
          provider_dlrn_hash_tag: "{{ dlrn_hash_tag|default('') }}"
          provider_job_branch: "{{ provider_job_branch }}"
          registry_ip_address_branch: "{{ registry_ip_address_branch }}"
          provider_dlrn_hash_branch: "{{ provider_dlrn_hash_branch }}"
      tags:
        - skip_ansible_lint
