workspace: "{{ ansible_user_dir }}/workspace"
tripleo_root: "{{ ansible_user_dir }}/src/opendev.org/openstack"
tripleo_ci_dir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-ci'].src_dir }}"
tripleo_quickstart_dir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-quickstart'].src_dir }}"
vxlan_vars: "-e toci_vxlan_networking='false' -e vxlan_networking='false'"
extra_vars: ""
job_featureset_file: "{{ tripleo_quickstart_dir }}/config/general_config/featureset{{ featureset }}.yml"
skip_tags_list: >-
  {% if environment_type == 'baremetal' -%}
  tripleo-validations
  {%- else -%}
  tripleo-validations,teardown-all
  {%- endif -%}

featureset_conf: >-
  {% if common_featureset is defined -%}
  --extra-vars @{{ tripleo_quickstart_dir }}/config/general_config/{{ common_featureset }} {% endif -%}
  --extra-vars @{{ job_featureset_file }}

# "force_non_periodic" - will force job to run as check job, no matter which pipeline it runs
# "force_periodic" - will force job to run as periodic (in terms of TripleO CI), no matter which pipeline it runs
periodic: >-
  {% if ('periodic' in zuul.pipeline and not force_non_periodic|default(false)|bool) or (force_periodic|default(false)|bool) -%}
  true
  {%- else -%}
  false
  {%- endif %}

nodepool_provider: "{{ hostvars[inventory_hostname].nodepool.provider }}"

rhcloud: >-
  {%- if nodepool_provider in ['rdo-cloud-tripleo', 'rdo-cloud'] -%}
  rdocloud
  {%- elif nodepool_provider == 'vexxhost-rdo-ca-ymq-1' -%}
  vexxhost
  {%- elif nodepool_provider == 'tripleo-ci' and environment_type == 'ovb' -%}
  internal
  {%- endif -%}

nodes_file: >-
  {% if nodes is defined -%}
  {{ tripleo_quickstart_dir }}/config/nodes/{{ nodes }}.yml
  {%- endif %}

nodes_args: >-
  {% if nodes is defined -%}
  --extra-vars @{{ nodes_file }}
  {%- endif %}

rdo_env_vars: >-
  {% if rhcloud -%}
  --extra-vars @{{ tripleo_ci_dir }}/toci-quickstart/config/testenv/{{ environment_type }}-{{ rhcloud }}.yml
  {%- endif %}

env_vars: "--extra-vars @{{ tripleo_ci_dir }}/toci-quickstart/config/testenv/{{ environment_type }}.yml {{ rdo_env_vars }}"
